server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: microservice-template
  profiles:
    active: dev
    
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true

# Default Actuator Configuration (overridden in profiles)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
    info:
      access: unrestricted
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Default Logging Configuration (overridden in profiles)
logging:
  level:
    '[com.template]': INFO
    '[org.springframework]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-},%X{requestId:-}] %logger{36} - %msg%n"
  file:
    path: ./logs

# JWT Configuration
app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationAndValidationThatShouldBeVeryLongAndSecure
    expiration: 86400  # 24 hours in seconds
