spring:
  profiles:
    active: dev

  # Development Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/template_dev
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000  # JPA Configuration for Development  
  jpa:
    hibernate:
      # Disable auto DDL since we're using Flyway
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  
  # Flyway specific configuration for dev profile
  flyway:
    baseline-on-migrate: true
    clean-disabled: false

  # Redis Configuration for Development
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    
    # MongoDB Configuration for Development
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:template_dev}
      username: ${MONGO_USERNAME:}
      password: ${MONGO_PASSWORD:}

  # Kafka Configuration for Development
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: template-dev-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

# Actuator Configuration for Development (All endpoints exposed)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

# Development Logging Configuration
logging:
  level:
    '[com.template]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.kafka]': INFO
    '[org.springframework.data.mongodb]': DEBUG
    '[org.springframework.data.redis]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
